## name: Cosmic Cyberpunk
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Cosmic-Cyberpunk-Kitten-Theme

background            #000b1e
foreground            #749ffe
selection_background  #1c61c2
selection_foreground  #749ffe
cursor                #6300cf
cursor_text_color     #000b1e

color0                #000b1e
color8                #1c61c2
color7                #749ffe
color15               #749ffe

color1                #ff0000
color9                #ff0000

color2                #8210ff
color10               #8210ff

color3                #f57800
color11               #ff5780

color4                #133e7c
color12               #00ff00

color5                #6300cf
color13               #6300cf

color6                #749ffe
color14               #749ffe
