background            #1e1d40
foreground            #ffffff
cursor                #fad000
cursor_text_color     #1e1d40
selection_background  #b362ff
selection_foreground  #ffffff
color0                #000000
color8                #686868
color1                #d90429
color9                #f92a1c
color2                #3ad900
color10               #43d426
color3                #ffe700
color11               #f1d000
color4                #6943ff
color12               #6872ff
color5                #ff2b70
color13               #ff77ff
color6                #00c5c7
color14               #79e8fb
color7                #c7c7c7
color15               #ffffff
