# xcodedark by arzg
# https://github.com/arzg/vim-colors-xcode
# License: MIT

background  #292a30
foreground  #dfdfe0
cursor      #53606e
cursor_text_color #292a30
selection_foreground  #53606e
selection_background  #393b44

color0  #292a30
color8  #53606e

color1  #ff8170
color9  #ff7ab2

color2  #78c2b3
color10 #acf2e4

color3  #ffa14f
color11 #d9c97c

color4  #4eb0cc
color12 #6bdfff

color5  #b281eb
color13 #dabaff

color6  #84b360
color14 #b0e687

color7  #a3b1bf
color15 #53606e
